config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'welcome#index'

  get 'publications/search' => 'publications#search'
  resources :publications do
    resources :reviews
    resources :rewards
  end

  post 'charges' => 'charges#create'

  resources :users, only: [:show]

end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :genre
  belongs_to :user
  has_many :reviews
  has_many :rewards
  has_one :campaign

  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :user
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show]
  before_action :set_user_publication, only: [:edit, :update, :destroy]
  before_action :verify_user, only: [:new, :edit, :create, :update, :destroy]
  before_action :verify_publication_author, only: [:edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  def search
    @publications = Publication.search(params[:q] || '')
    render 'index'
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    @review = Review.new
    @publication
  end

  # GET /publications/new
  def new
    @publication = current_user.publications.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = current_user.publications.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.preload(:rewards).find(params[:id])
    end

    def set_user_publication
      @publication = current_user.publications.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params[:publication].permit(:title, :description, :genre_id)
    end

    def verify_publication_author
      render status: :not_found and return if @publication.user != current_user
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_for(@publication) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= f.label :title %><br />
  <%= f.text_field :title, autofocus: true %></div>

  <div><%= f.label :description %><br />
  <%= f.text_area :description %></div>

  <div><%= f.label :genre_id %><br /></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/_tiles.html.erb
<div class="publication-tiles">
<% puts publications %>
<% if publications.nil? %>
This author currently has no publications.
<% else %>
<% publications.shuffle.each do |publication| %>
    <div class="item clearfix genre-<%= publication.genre_id.to_s %> size-<%= publication.title.split().length.to_s %>">
        <p class="text title"><%= link_to publication.title, publication_url(publication.id) %></p>
        <p class="text description"><%= publication.description %></p>
    </div>
<%end %>
<% end %>
</div>

<style>

.item {
    min-width: 25%;
    max-width: 50%;
    background-image: url(<%= image_url('shattered.png') %>);
}

.item p {
    margin-left: 10px;
}

.item .title {
    text-decoration: none;
    top: 53px;
    left: 3%;
    font-style: inherit;
    font-size: 2.5em;
    font-weight: 700;
}

.item .description {
    font-family: "Open Sans Condensed";
    font-style: italic;
    font-weight: 300;
}

.item.genre-1 {
    background-color: #23A38F;
}

.genre-2 {
    background-color: #B7C11E;
}

.genre-3 {
    background-color: #EFF1C2;
}

.genre-4 {
    background-color: #F0563D;
}

.genre-5 {
    background-color: #2E313D;
}

.size-2 {
    height: 320px;
    width: 320px;
}

.size-1 {
    width: 160px;
    height: 480px;
}

.size-3 {
    width: 480px;
    height: 160px;
}

.item * { 
    color: #FFF;
}

</style>

<script>

var wall = new freewall($(".publication-tiles")[0]);
wall.fitWidth($(".publication-tiles").width());


</script>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<h1>Listing publications</h1>

<%= render partial: 'tiles', locals: {publications: @publications} %>

<br>
<% if current_user %>
<%= link_to 'New Publication', new_publication_path %>
<% end %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render 'form' %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<div class="page-header">
  <h1><%= @publication.title %> <small>by <%= @publication.user.first_name %> <%= @publication.user.last_name %></small></h1>
</div>

<div class="row">
<div class="col-xs-8">
  <p><%= @publication.description %></p>

  <p>Want to check out the book?</p>
  <button type="button" class="btn btn-success btn-lg active">Download Free Chapter!</button>
</div>
<div class="col-xs-4">
<% if !@publication.rewards.empty? %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Contribute now!</h3>
  </div>
  <div class="panel-body">
    <p>Like what you see? Want to see more? Support <%= @publication.user.first_name %> <%= @publication.user.last_name %> and <%= @publication.title %> by contributing today!</p>

    <% @publication.rewards.each do |reward| %>
      <div class="reward" data-id="<%= reward.id %>" data-title="<%= reward.title %>" data-amount="<%= (reward.price * 100).to_i %>">
        <div class="price-thing">Pledge <span class="price"><%= reward.price %></span> or more</div>
        <div class="desc-ting">
          <span class="title"><%= reward.title %></span><span class="description"><%= reward.description %></span>
        </div>
      </div>
    <% end %>

    <% if current_user.nil? %>
      <a type="button" href="<%= new_user_session_path %>" class="btn btn-success btn-lg btn-block">Login to contribute!</a>
    <% else %>
      <button type="button" class="btn disabled btn-primary btn-lg btn-block">Take my money!</button>
    <% end %>
  </div>
</div>
<% end %>
</div>
</div>

<style>

.reward {
  margin-bottom: 1em;
}
.reward.active {
  font-weight: 700;
}

.reward .title:after {
  content: " - ";
}

.reward .price:before {
  content: "$";
}
</style>

<script src="https://checkout.stripe.com/checkout.js"></script>
<script>
var email = "<%= '' if current_user.nil? or current_user.email %>",
  handler = StripeCheckout.configure({
  key: 'pk_test_7to8XU3q719PFi9D3nmQ4iVt',
  //image: '/square-image.png',
  token: function(token) {
    var data = {
      charge: {
        token: token.id,
        reward_id: rewardId
      }
    };

    $.post('<%= charges_path %>', data, function () {
      console.log('success');
    });

    // Use the token to create the charge with a server-side script.
    // You can access the token ID with `token.id`
  }
});

$(".reward").on('click', function() {
  var data = $(this).data();
  rewardId = data.id;
  $(this).siblings().removeClass('active');
  $(this).addClass('active');


  $("button.btn-block.btn-primary").off('click');
  $("button.btn-block.btn-primary").on('click', function(e) {
    handler.open({
      name: 'Pulp Fiction',
      email: email,
      description: data.title,
      amount: data.amount
    });
  });
  $("button.btn-block.btn-primary").removeClass('disabled');
});

</script>

<div class="reviews-container row">
  <div class="col-xs-12">
  	<% if @publication.reviews.nil? || @publication.reviews.length == 0 %>
  	No reviews yet. Why don't you write one?
  	<% else %>
      <h3>Reviews</h3>
  		<% @publication.reviews.each do |review| %>
  			<%= render partial: '/reviews/show', locals: {review: review} %>
  		<% end %>
  	<% end %>
  </div>
</div>

<div class="reviews-form row">
  <div class="col-xs-8">
    <h3>Write a new review</h1>
    <%= render partial: '/reviews/form' %>
  </div>
</div>

<% if current_user && current_user.id == @publication.user_id %>
<%= link_to 'Edit', edit_publication_path(@publication) %> | <%= link_to 'Add Rewards', publication_rewards_path(@publication) %> | 
<% end %>
<%= link_to 'Back', publications_path %>