config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'welcome#index'

  get 'publications/search' => 'publications#search'
  resources :publications do
    resources :reviews
    resources :rewards
  end

  post 'charges' => 'charges#create'

  resources :users, only: [:show]

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :publication
  has_many :charges
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_publication
  before_action :set_reward, only: [:show, :edit, :update, :destroy]

  # GET /publications/1/rewards
  # GET /publications/1/rewards.json
  def index
    @rewards = @publication.rewards.all
  end

  # GET /publications/1/rewards/1
  # GET /publications/1/rewards/1.json
  def show
  end

  # GET /publications/1/rewards/new
  def new
    @reward = @publication.rewards.new
  end

  # GET /publications/1/rewards/1/edit
  def edit
  end

  # POST /publications/1/rewards
  # POST /publications/1/rewards.json
  def create
    @reward = @publication.rewards.new(reward_params)

    respond_to do |format|
      if @reward.save
        format.html { redirect_to @publication, notice: 'Reward was successfully created.' }
        format.json { render :show, status: :created, location: @reward }
      else
        format.html { render :new }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1/rewards/1
  # PATCH/PUT /publications/1/rewards/1.json
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to @publication, notice: 'Reward was successfully updated.' }
        format.json { render :show, status: :ok, location: @reward }
      else
        format.html { render :edit }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1/rewards/1
  # DELETE /publications/1/rewards/1.json
  def destroy
    @reward.destroy
    respond_to do |format|
      format.html { redirect_to publication_rewards_url, notice: 'Reward was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_publication
      @publication = Publication.find( params[:publication_id])
    end

    def set_reward
      @reward = @publication.rewards.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reward_params
      params[:reward].permit(:title, :description, :limit, :price)
    end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_for([@publication, @reward]) do |f| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% @reward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div><%= f.label :title %><br />
  <%= f.text_field :title, autofocus: true %></div>

  <div><%= f.label :description %><br />
  <%= f.text_area :description %></div>


  <div><%= f.label :limit %><br />
  <%= f.text_field :limit %></div>

  <div><%= f.label :price %><br />
  <%= f.text_field :price %></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing reward</h1>

<%= render 'form' %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', publication_rewards_path %>

app/views/rewards/index.html.erb
<h1>Listing rewards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rewards.each do |reward| %>
      <tr>
        <td><%= link_to 'Show', [@publication, reward] %></td>
        <td><%= link_to 'Edit', edit_publication_reward_path(@publication, reward) %></td>
        <td><%= link_to 'Destroy', [@publication, reward], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reward', new_publication_reward_path %>

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render 'form' %>

<%= link_to 'Back', publication_rewards_path %>

app/views/rewards/show.html.erb
<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>