config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'welcome#index'

  get 'publications/search' => 'publications#search'
  resources :publications do
    resources :reviews
    resources :rewards
  end

  post 'charges' => 'charges#create'

  resources :users, only: [:show]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_publication
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :verify_user, only: [:new, :edit, :create, :update, :destroy]
  before_action :verify_review_author, only: [:edit, :update, :destroy]

  # GET /publications/1/reviews
  # GET /publications/1/reviews.json
  def index
    @reviews = @publication.reviews.all
  end

  # GET /publications/1/reviews/1
  # GET /publications/1/reviews/1.json
  def show
  end

  # GET /publications/1/reviews/new
  def new
    @review = @publication.reviews.new
  end

  # GET /publications/1/reviews/1/edit
  def edit
  end

  # POST /publications/1/reviews
  # POST /publications/1/reviews.json
  def create
    @review = @publication.reviews.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review.publication, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1/reviews/1
  # PATCH/PUT /publications/1/reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review.publication, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1/reviews/1
  # DELETE /publications/1/reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to publication_reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_publication
      @publication = Publication.find(params[:publication_id])
    end

    def set_review
      @review = @publication.reviews.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params[:review].permit(:title, :content)
    end

    def verify_review_author
      render status: :not_found and return if @review.user != current_user
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@publication, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= f.label :title %><br />
  <%= f.text_field :title, autofocus: true %></div>

  <div><%= f.label :content %><br />
  <%= f.text_area :content %></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= review.title %></h3>
  </div>
  <div class="panel-body">
    <%= review.content %>
  </div>
  <!-- <div class="panel-footer"><%= review.user_id %></div> -->
</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', publication_reviews %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', publication_reviews %>

app/views/reviews/show.html.erb
<%= link_to 'Edit', edit_publication_review(@review) %> |
<%= link_to 'Back', publication_reviews %>